name: build
on:
  workflow_dispatch:
jobs:
  build_image_and_push_to_registry:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build image
        run: |
          chmod +x ./build.sh
          ./build.sh
